### ISSUE TITLE
self-hosted runners

### ISSUE THREAD

**Issue by mudler** [go-skynet/LocalAI#305]
After discussing on discord, we really would like to set up tests for each model family - however GH runners aren't capable enough (both in size and HW capacity) and results in long runs.

We could have runners instead, to perform more automated test to catch up any regression. 

## Todo

- [ ] Where to host the runner?
- [ ] Set it up
- [ ] Wire e2e tests in the pipeline to it

**Comment by mudler** [comment]
closing as we have self-hosted for GPUs, CI pipeline is being worked out in #1095
